# Generated by Django 3.1.4 on 2021-03-03 16:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Materiales',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_producto', models.CharField(max_length=100)),
                ('marca', models.CharField(max_length=99)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizado', models.DateTimeField(auto_now=True)),
                ('codigo', models.CharField(blank=True, max_length=100, unique=True)),
                ('imagen', models.ImageField(upload_to='images/')),
            ],
            options={
                'verbose_name': 'material',
                'verbose_name_plural': 'materiales',
                'db_table': 'materiales',
            },
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_proveedor', models.CharField(max_length=99)),
                ('ruc', models.CharField(max_length=99)),
                ('telefono', models.CharField(max_length=15)),
                ('direccion', models.CharField(max_length=99)),
                ('email', models.EmailField(max_length=99)),
                ('creacion_proveedor', models.DateTimeField(auto_now_add=True)),
                ('ultima_modificacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Proveedor',
                'verbose_name_plural': 'Proveedores',
                'db_table': 'proveedores',
            },
        ),
        migrations.CreateModel(
            name='OrdenesCompraMateriales',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_factura', models.CharField(max_length=333)),
                ('cantidad', models.PositiveBigIntegerField(default=0)),
                ('codigo', models.CharField(max_length=100)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='materiales.materiales')),
                ('nombre_proveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='materiales.proveedor')),
            ],
            options={
                'verbose_name': 'orden de compra',
                'verbose_name_plural': 'ondenes de compras',
                'db_table': 'ordenes_de_compras',
            },
        ),
    ]
