# Generated by Django 3.1.4 on 2021-03-03 16:34

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('materiales', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clientes',
            fields=[
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('cedula', models.CharField(error_messages={'unique': 'El cliente con este número de cédula ya existe'}, max_length=10, primary_key=True, serialize=False)),
                ('telefono_celular', models.CharField(max_length=10)),
                ('address', models.CharField(max_length=100)),
                ('fecha_de_instalacion', models.DateTimeField(default=datetime.datetime(2021, 3, 3, 11, 34, 55, 416296))),
                ('email', models.EmailField(max_length=100)),
                ('activo', models.BooleanField()),
            ],
            options={
                'verbose_name': 'cliente',
                'verbose_name_plural': 'clientes',
                'db_table': 'clientes',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ContratoClientes',
            fields=[
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('cedula', models.CharField(error_messages={'unique': 'El cliente con este número de cédula ya existe'}, max_length=10, primary_key=True, serialize=False)),
                ('telefono_celular', models.CharField(max_length=10)),
                ('address', models.CharField(max_length=100)),
                ('fecha_contrato', models.DateTimeField(default=datetime.datetime(2021, 3, 3, 11, 34, 55, 415829))),
                ('valor_contrato', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('instalado', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'contrato-clientes',
            },
        ),
        migrations.CreateModel(
            name='PagosMensualidadesClientes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(default=datetime.datetime.now)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=6)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clientes.clientes')),
            ],
            options={
                'verbose_name': 'pago',
                'verbose_name_plural': 'pagos',
                'db_table': 'pagos_mensualidades_clientes',
            },
        ),
        migrations.CreateModel(
            name='OrdenesTrabajoClientes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_orden', models.CharField(max_length=333)),
                ('pago_materiales', models.BooleanField(default=False)),
                ('cantidad', models.PositiveIntegerField(default=0)),
                ('descripcion_actividad', models.CharField(choices=[('IN', 'Instalacion nueva'), ('CD', 'Cambio de domicilio'), ('AR', 'ARREGLO'), ('AD', 'Adicionales'), ('RI', 'Reinstalaciones'), ('SV', 'Suspencion voluntaria'), ('CS', 'Cortes de Servicio')], max_length=2)),
                ('fecha_trabajo', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clientes.clientes')),
                ('materiales', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='materiales.materiales')),
            ],
            options={
                'verbose_name': 'orden de trabajo',
                'verbose_name_plural': 'ordenes de trabajo',
                'db_table': 'ordenes de trabajo clientes',
            },
        ),
    ]
