# Generated by Django 3.1.4 on 2021-03-11 16:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_auto_20210304_1809'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientes',
            name='telefono_domicilio',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contratoclientes',
            name='telefono_domicilio',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='clientes',
            name='fecha_de_instalacion',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 11, 11, 2, 23, 408665)),
        ),
        migrations.AlterField(
            model_name='contratoclientes',
            name='fecha_contrato',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 11, 11, 2, 23, 408088)),
        ),
    ]
